config/routes.rb
Rails.application.routes.draw do
  root to: 'holiday_checker#index'
  resource :holiday_checker, only: [:index, :update], controller: :holiday_checker do
    get :success
    get :failure
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/holiday_checker_controller.rb
class HolidayCheckerController < ApplicationController
  def update
    date = DateTime.strptime(params[:picked_date][:date], '%d-%m-%Y')

    if IsDateHolidayCheckService.new(date).exec
      redirect_to success_holiday_checker_path
    else
      redirect_to failure_holiday_checker_path
    end
  end

  def success
  end

  def failure
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/holiday_checker/failure.haml
.alert.alert-danger
  Failure
= link_to 'Back', root_path, class: 'btn btn-default'

app/views/holiday_checker/failure.html.haml
.alert.alert-danger
  Failure
= link_to 'Back', root_path, class: 'btn btn-default'

app/views/holiday_checker/index.html.haml
.panel.panel-default
  .panel-heading
    Pick day
  .panel-body
    = simple_form_for :picked_date, url: holiday_checker_path, method: :put do |f|
      = f.input :date, input_html: { class: 'datepicker' }
      = f.button :submit, 'Submit'

app/views/holiday_checker/success.haml
.alert.alert-success
  Success
= link_to 'Back', root_path, class: 'btn btn-default'

app/views/holiday_checker/success.html.haml
.alert.alert-success
  Success
= link_to 'Back', root_path, class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CubeDemoDay
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .row
        .col-sm-4.col-sm-offset-4
          = yield